name: Salesforce CI/CD - to master

on:
    pull_request:
      branches: [ master ]
      paths:
        - 'force-app/**'
jobs:
  pipeline:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository files 
        uses: actions/checkout@v2
        
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{secrets.SFDX_URL}}
      - name: create xml
        run: sfdx force:source:manifest:create --sourcepath force-app --manifestname package.xml
      - name: sfdx-actions
        run: | 
          echo "current directory `pwd`"
          echo "all files: `ls -a`"
          sfdx force:source:deploy -w 100 --ignorewarnings --manifest package.xml
